baseURL: /
languageCode: en-us
title: All Nations Cafe International

# Theme settings
module:
  imports:
   - path: github.com/biomassives/allnationscafe-int-hugo-parsa-forestry
     mounts:
     - source: layouts
       target: layouts
     - source: assets
       target: assets
     - source: static
       target: static
     - source: exampleSite/static/images
       target: static/images

summaryLength: '10'
paginate: 6
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/headroom/headroom.js
      - link: plugins/instafeed/instafeed.min.js
      - link: plugins/masonry/masonry.js
      - link: plugins/reading-time/readingTime.min.js
      - link: plugins/smooth-scroll/smooth-scroll.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js
  logo: images/logo.png
  home: Home
  layout: '1'
  description: Israeli and Palestinian residents of Jerusalem and environs share physical space on a daily basis, in the supermarket, the gyms, pools, the parks, buses, and health care clinics. However, they rarely interact with any more than a superficial greeting. We believe that a true and lasting peace on the ground is possible only if we deepen our understanding of the “other,” facilitating a move beyond fear of the unknown and into the intimately familiar.
  preloader: true
  search: true
  author: Themefisher
  author_image: images/banner-img.png
  bio: >-
      All Nations Cafe International
  mobile: +01 720 297 6965
  email: info@allnations.cafe
  address: P.O. Box 911 Nederland CO 80466
  contact_form_action: '#'
  google_analitycs_id: Your ID
  copyright: 'Copyright &copy; 2021 All Nations Cafe International'
  instafeed:
    enable: true
    access_token: >-
      IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social:
    - icon: ti-facebook
      URL: '#'
    - icon: ti-twitter-alt
      URL: 'https://twitter.com/allnationscafe'
    - icon: ti-github
      URL: 'https://github.com/biomassives/allnationscafe-int-hugo-parsa-forestry'
menu:
  main:
    - name: About
      URL: about
      weight: 2
    - name: Contact
      URL: contact
      weight: 3
